function decisionClass(status){return(status==='BUY SETUP'||status==='SELL SETUP')?'buy':status==='WAIT'?'wait':status==='PASS'?'pass':'checking'}
function qKey(item){return`${item.ticker}|${ymd(item.date)}`}

async function qualifySignal(item,earningsInfo=null){
  const key=qKey(item);if(qualificationCache.has(key))return qualificationCache.get(key);
  const result={status:'WAIT',reason:'Checking current market data…',gates:[]};qualificationCache.set(key,result);
  try{
    const dailyRows=await getPrices(item.ticker),hourlyRows=await getHourly(item.ticker),daily=dailyMetrics(dailyRows,item.signal.dir),hourly=hourlyMetrics(hourlyRows,item.signal.dir),season=seasonalGate(item);
    const today=new Date(),today0=new Date(today.getFullYear(),today.getMonth(),today.getDate()),end=projectedEnd(item.date),active=today0>=item.date&&today0<=end,future=today0<item.date,expired=today0>end;
    if(!earningsInfo){const map=await fetchEarningsBatch([item.ticker]);earningsInfo=map[item.ticker]}
    const earningsKnown=earningsInfo?.complete===true,earningsEvent=earningsInfo?.event||null,earningsDays=earningsEvent?marketDaysUntil(today0,earningsEvent.date):99,earningsConflict=earningsKnown&&earningsEvent&&earningsDays>=0&&earningsDays<=7;
    let moveUsed=0,realized=0;if(active&&daily.ok){realized=realizedSeasonMove(dailyRows,item,daily.lastClose);moveUsed=Math.max(0,Math.round(realized/Math.max(Math.abs(item.signal.avg),.01)*100))}
    const notSpent=!active||moveUsed<MAX_MOVE_USED;
    let rr=null,target=null;if(hourly.ok&&daily.ok){const remaining=Math.max(0,Math.abs(item.signal.avg)-Math.max(0,realized));target=item.signal.dir==='up'?hourly.entry*(1+remaining/100):hourly.entry*(1-remaining/100);const risk=item.signal.dir==='up'?hourly.entry-daily.stop:daily.stop-hourly.entry,reward=item.signal.dir==='up'?target-hourly.entry:hourly.entry-target;if(risk>0&&reward>0)rr=reward/risk}
    const rrPass=Number.isFinite(rr)&&rr>=MIN_RR;
    result.metrics={moveUsed,realized,rr,target,stop:daily.stop,entry:hourly.entry,pullbackAtr:daily.pullbackAtr,earningsEvent,earningsKnown,dailyDate:daily.lastDate,hourlyTime:hourly.lastTime};
    result.gates=[
      {label:'Seasonal edge',state:season.pass?'ok':'no',value:season.details},
      {label:'Seasonal window active',state:active?'ok':expired?'no':'pending',value:active?'ACTIVE':expired?'EXPIRED':`Starts ${fmtShort(ymd(item.date))}`},
      {label:'Daily trend aligned',state:daily.ok?(daily.trend?'ok':'no'):'pending',value:daily.ok?(daily.trend?'YES':'NO'):'DATA'},
      {label:'0.5–1.5 ATR pullback',state:daily.ok?(daily.pullback?'ok':'pending'):'pending',value:daily.ok?`${daily.pullbackAtr.toFixed(2)} ATR`:'DATA'},
      {label:'Seasonal move used <70%',state:notSpent?'ok':'no',value:active?`${moveUsed}%`:'0%'},
      {label:'Latest completed 1H trigger',state:hourly.ok?(hourly.trigger?'ok':'pending'):'pending',value:hourly.ok?(hourly.trigger?'CONFIRMED':'NOT YET'):'DATA'},
      {label:'No earnings in next 7 trading days',state:!earningsKnown?'pending':earningsConflict?'no':'ok',value:!earningsKnown?'UNKNOWN':earningsConflict?earningsEvent.date:'CLEAR'},
      {label:'Expected reward ≥1.5R',state:Number.isFinite(rr)?(rrPass?'ok':'pending'):'pending',value:Number.isFinite(rr)?`${rr.toFixed(2)}R`:'WAIT'}
    ];
    const hardFail=!season.pass||expired||(daily.ok&&!daily.trend)||!notSpent||earningsConflict;
    const dataPending=!daily.ok||!hourly.ok||!earningsKnown;
    if(hardFail){result.status='PASS';if(!season.pass)result.reason='The seasonal statistics do not meet the mechanical minimums.';else if(expired)result.reason='This seasonal window has already expired.';else if(daily.ok&&!daily.trend)result.reason='The current Daily trend conflicts with the seasonal direction.';else if(!notSpent)result.reason='Too much of the expected seasonal move has already occurred.';else result.reason=`Earnings are scheduled within the next 7 trading days (${earningsEvent.date}).`}
    else if(dataPending){result.status='WAIT';result.reason='A required market-data gate is unavailable, so the system will not issue an actionable BUY/SELL setup.'}
    else if(future){result.status='WAIT';result.reason=`The setup is qualified for monitoring, but the seasonal window does not start until ${fmtShort(ymd(item.date))}.`}
    else if(!daily.pullback){result.status='WAIT';result.reason=daily.pullbackAtr<PULLBACK_MIN_ATR?'Price has not pulled back enough yet.':'The pullback is deeper than the allowed 1.5 ATR window.'}
    else if(!hourly.trigger){result.status='WAIT';result.reason='The Daily setup is ready, but the latest completed 1H candle has not confirmed the entry trigger.'}
    else if(!rrPass){result.status='WAIT';result.reason='The current entry location does not provide the required 1.5R expected reward.'}
    else{result.status=item.signal.dir==='up'?'BUY SETUP':'SELL SETUP';result.reason='Every mechanical gate currently passes: seasonality, trend, pullback, 1H trigger, earnings and risk/reward.'}
    qualificationCache.set(key,result);return result;
  }catch(e){result.status='WAIT';result.reason=`Current qualification data could not be completed: ${e?.message||'data error'}`;result.gates=[{label:'Market-data check',state:'pending',value:'RETRY'}];qualificationCache.set(key,result);return result}
}

function setStatus(text,mode='loading'){const box=$('statusBox');box.classList.remove('hidden','error');if(mode==='hidden'){box.classList.add('hidden');return}if(mode==='error')box.classList.add('error');$('statusText').textContent=text}
function renderBlankCalendar(){const y=current.getFullYear(),m=current.getMonth();$('monthTitle').textContent=current.toLocaleString('en-US',{month:'long',year:'numeric'});const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),today=new Date(),grid=$('grid');grid.innerHTML='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const cell=document.createElement('div');cell.className='day'+(d.getMonth()!==m?' other':'')+(ymd(d)===ymd(today)?' today':'');const num=document.createElement('div');num.className='num';num.textContent=d.getDate();cell.appendChild(num);grid.appendChild(cell)}}
function renderCalendar(signals){const y=current.getFullYear(),m=current.getMonth();$('monthTitle').textContent=current.toLocaleString('en-US',{month:'long',year:'numeric'});const byDate=new Map();for(const s of signals){const key=ymd(s.date);if(!byDate.has(key))byDate.set(key,[]);byDate.get(key).push(s)}for(const arr of byDate.values())arr.sort((a,b)=>signalStrength(b.signal)-signalStrength(a.signal));const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),today=new Date(),grid=$('grid');grid.innerHTML='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const cell=document.createElement('div');cell.className='day'+(d.getMonth()!==m?' other':'')+(ymd(d)===ymd(today)?' today':'');const num=document.createElement('div');num.className='num';num.textContent=d.getDate();cell.appendChild(num);if(d.getMonth()===m){const ev=byDate.get(ymd(d))||[];ev.slice(0,3).forEach(item=>{const b=document.createElement('button'),q=qualificationCache.get(qKey(item));b.className=`stock ${item.signal.dir}`;b.textContent=`${item.signal.dir==='up'?'↑':'↓'} ${item.ticker} ${Math.round(item.signal.win)}%${q&&(q.status==='BUY SETUP'||q.status==='SELL SETUP')?` · ${q.status==='BUY SETUP'?'BUY':'SELL'}`:''}`;b.onclick=()=>openModal(item);cell.appendChild(b)});if(ev.length>3){const more=document.createElement('div');more.className='more';more.textContent=`+${ev.length-3} more`;cell.appendChild(more)}}grid.appendChild(cell)}$('emptyHint').style.display=signals.length?'none':'block'}
function renderTop(signals){const now=new Date();let candidates=signals;if(current.getFullYear()===now.getFullYear()&&current.getMonth()===now.getMonth())candidates=signals.filter(x=>x.date>=new Date(now.getFullYear(),now.getMonth(),now.getDate()));candidates=[...candidates].sort((a,b)=>signalStrength(b.signal)-signalStrength(a.signal)).slice(0,3);const el=$('topcards');el.innerHTML='';if(!candidates.length){const d=document.createElement('div');d.className='topcard';d.style.cursor='default';d.innerHTML='<div><div class="ticker">No strong signals</div><div class="sub">Nothing met the historical threshold in the upcoming dates shown.</div></div>';el.appendChild(d);return}for(const item of candidates){const end=projectedEnd(item.date),q=qualificationCache.get(qKey(item)),b=document.createElement('button');b.className='topcard';b.innerHTML=`<div><div class="ticker">${item.ticker}</div><div class="sub">${fmtShort(ymd(item.date))} – ${fmtShort(ymd(end))} · ${item.signal.years} years${q?` · ${q.status}`:''}</div></div><div class="score ${item.signal.dir}">${item.signal.dir==='up'?'↑':'↓'} ${Math.round(item.signal.win)}%</div>`;b.onclick=()=>openModal(item);el.appendChild(b)}}

function readinessCandidates(){const today=new Date(),start=new Date(today.getFullYear(),today.getMonth(),today.getDate()),cutoff=addMarketDays(start,5),eligible=currentSignals.filter(x=>projectedEnd(x.date)>=start&&x.date<=cutoff).sort((a,b)=>signalStrength(b.signal)-signalStrength(a.signal));const seen=new Set(),out=[];for(const x of eligible){if(seen.has(x.ticker))continue;seen.add(x.ticker);out.push(x);if(out.length>=8)break}return out}
async function renderReadiness(){const el=$('readycards'),items=readinessCandidates();if(!items.length){el.innerHTML='<div class="readycard" style="cursor:default"><div><div class="ticker">No near-term candidates</div><div class="sub">No historical signal starts or remains active within the next five trading days.</div></div><span class="decision pass">NONE</span></div>';return}el.innerHTML=items.map(x=>`<div class="readycard" data-qkey="${qKey(x)}" style="cursor:default"><div><div class="ticker">${x.ticker}</div><div class="sub">Checking ${x.signal.dir==='up'?'bullish':'bearish'} setup…</div></div><span class="decision checking">CHECK</span></div>`).join('');const earnings=await fetchEarningsBatch(items.map(x=>x.ticker));await pool(items,3,async item=>{const q=await qualifySignal(item,earnings[item.ticker]),card=el.querySelector(`[data-qkey="${qKey(item)}"]`);if(card){card.style.cursor='pointer';card.querySelector('.sub').textContent=`${item.signal.dir==='up'?'Bullish':'Bearish'} · ${Math.round(item.signal.win)}% · ${q.reason}`;const pill=card.querySelector('.decision');pill.className=`decision ${decisionClass(q.status)}`;pill.textContent=q.status==='BUY SETUP'?'BUY':q.status==='SELL SETUP'?'SELL':q.status;card.onclick=()=>openModal(item)}});renderCalendar(currentSignals);renderTop(currentSignals)}

function renderModalQualification(q){const pill=$('mDecision');pill.className=`decision ${decisionClass(q.status)}`;pill.textContent=q.status;$('mReason').textContent=q.reason;const gates=$('mGates');gates.innerHTML='';for(const g of q.gates||[]){const row=document.createElement('div');row.className=`gate ${g.state}`;row.innerHTML=`<span class="glabel">${g.label}</span><span class="gval">${g.value}</span>`;gates.appendChild(row)}if(q.metrics&&Number.isFinite(q.metrics.entry)&&Number.isFinite(q.metrics.stop)){const row=document.createElement('div');row.className='gate ok';row.innerHTML=`<span class="glabel">Mechanical entry / stop</span><span class="gval">${q.metrics.entry.toFixed(2)} / ${q.metrics.stop.toFixed(2)}</span>`;gates.appendChild(row)}}
function openModal(item){modalItem=item;const s=item.signal,end=projectedEnd(item.date);$('mTicker').textContent=item.ticker;$('mWindow').textContent=`${fmtShort(ymd(item.date))} – ${fmtShort(ymd(end))} · ${WINDOW_DAYS} trading days`;const badge=$('mBadge');badge.textContent=s.dir==='up'?'Bullish':'Bearish';badge.className=`badge ${s.dir}`;$('mWin').textContent=Math.round(s.win)+'%';$('mAvg').textContent=pct(s.avg);$('mMedian').textContent=pct(s.median);$('mYears').textContent=s.years;$('mDirection').textContent=s.dir==='up'?'Up':'Down';$('mStrength').textContent=s.win>=80?'High':s.win>=75?'Good':'Watch';const rows=$('mRows');rows.innerHTML='';[...s.rows].sort((a,b)=>a.year-b.year).forEach(r=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${r.year}</td><td class="${r.ret>=0?'pos':'neg'}">${pct(r.ret)}</td><td>${fmtShort(r.start)}</td><td>${fmtShort(r.end)}</td>`;rows.appendChild(tr)});$('mSource').textContent='Seasonality uses Yahoo Finance adjusted Daily history. The qualifier uses the latest completed Daily and 1H market bars plus an earnings-calendar check. If a required data source is unavailable, the system returns WAIT rather than guessing.';$('modalWrap').classList.add('show');const cached=qualificationCache.get(qKey(item));if(cached)renderModalQualification(cached);else{$('mDecision').className='decision checking';$('mDecision').textContent='CHECKING';$('mReason').textContent='Loading current Daily, 1H and earnings data…';$('mGates').innerHTML='';qualifySignal(item).then(q=>{if(modalItem&&qKey(modalItem)===qKey(item))renderModalQualification(q);renderReadiness()})}}

async function analyzeMonth(force=false){if(isLoading)return;isLoading=true;if(force){memoryPrices.clear();hourlyCache.clear();qualificationCache.clear();earningsCache.clear()}renderBlankCalendar();$('topcards').innerHTML='';$('readycards').innerHTML='<div class="readycard" style="cursor:default"><div><div class="ticker">Checking setups…</div><div class="sub">Daily trend, ATR pullback, 1H trigger, earnings and risk/reward.</div></div><span class="decision checking">CHECK</span></div>';$('emptyHint').style.display='none';$('prev').disabled=true;$('next').disabled=true;const dates=tradingDatesInMonth(current),all=[];let completed=0,usable=0;setStatus(`Loading real historical data… 0/${TICKERS.length}`);try{await pool(TICKERS,4,async ticker=>{try{const rows=await getPrices(ticker,force);usable++;const raw=[];for(const date of dates){const signal=calculateSignalForDate(rows,date);if(signal)raw.push({ticker,date:new Date(date),signal})}all.push(...sparsifyTickerSignals(raw))}catch(err){console.warn(ticker,err)}completed++;setStatus(`Loading real historical data… ${completed}/${TICKERS.length}`)});currentSignals=all.sort((a,b)=>a.date-b.date||signalStrength(b.signal)-signalStrength(a.signal));renderCalendar(currentSignals);renderTop(currentSignals);if(usable===0)setStatus('Market data could not be loaded right now. No fake fallback numbers were inserted. Tap Retry in a moment.','error');else if(usable<TICKERS.length)setStatus(`Loaded ${usable} of ${TICKERS.length} stocks. Some data sources did not respond. Tap Retry to refresh.`,'error');else{setStatus(`Updated with real historical data · ${TICKERS.length} stocks scanned`);setTimeout(()=>setStatus('','hidden'),2600)}renderReadiness()}finally{$('prev').disabled=false;$('next').disabled=false;isLoading=false}}

$('prev').onclick=()=>{if(isLoading)return;current=new Date(current.getFullYear(),current.getMonth()-1,1);analyzeMonth(false)};$('next').onclick=()=>{if(isLoading)return;current=new Date(current.getFullYear(),current.getMonth()+1,1);analyzeMonth(false)};$('retryBtn').onclick=()=>analyzeMonth(true);$('close').onclick=()=>{$('modalWrap').classList.remove('show');modalItem=null};$('modalWrap').onclick=e=>{if(e.target.id==='modalWrap'){e.currentTarget.classList.remove('show');modalItem=null}};document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('modalWrap').classList.remove('show');modalItem=null}});
renderBlankCalendar();analyzeMonth(false);