import fs from 'node:fs/promises';
import path from 'node:path';
const TICKERS=['AAPL','MSFT','NVDA','AMZN','GOOGL','META','TSLA','AVGO','JPM','LLY','V','MA','COST','WMT','NFLX','AMD','QCOM','ORCL','CRM','ADP','HD','KO','PEP','XOM','UNH','MCD','BAC','C','GS','MS','BA','CAT','GE','RTX','LMT','DIS','NKE','SBUX','TGT','LOW','ABBV','MRK','PFE','TXN','MU','INTC','PANW','DE','COP','SCHW'];
const OUT=path.join(process.cwd(),'data','market.json'),pad=n=>String(n).padStart(2,'0'),sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function yahoo(ticker,start,end,interval){const q=new URLSearchParams({period1:String(Math.floor(start)),period2:String(Math.floor(end)),interval,events:'div,splits',includeAdjustedClose:interval==='1d'?'true':'false'});let err;for(const h of ['query1.finance.yahoo.com','query2.finance.yahoo.com']){try{const r=await fetch(`https://${h}/v8/finance/chart/${ticker}?${q}`,{headers:{'User-Agent':'Mozilla/5.0 (compatible; SeasonalityCalendar/4.0)','Accept':'application/json,text/plain,*/*'}});if(!r.ok)throw Error(`Yahoo ${r.status}`);const j=await r.json();if(j?.chart?.result?.[0])return j}catch(e){err=e;await sleep(500)}}throw err||Error('Yahoo unavailable')}
function dailyRows(j){const r=j.chart.result[0],q=r.indicators.quote[0],a=r.indicators.adjclose?.[0]?.adjclose;if(!Array.isArray(a))throw Error('adjusted close missing');const out=[];for(let i=0;i<r.timestamp.length;i++){const adj=a[i],c=q.close?.[i],h=q.high?.[i],l=q.low?.[i];if(![adj,c,h,l].every(Number.isFinite))continue;const d=new Date(r.timestamp[i]*1000),iso=`${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-${pad(d.getUTCDate())}`,f=c?adj/c:1;out.push({d:iso,a:+adj.toFixed(5),ah:+(h*f).toFixed(5),al:+(l*f).toFixed(5)})}return out}
function hourlyRows(j){const r=j.chart.result[0],q=r.indicators.quote[0],out=[];for(let i=0;i<r.timestamp.length;i++){const c=q.close?.[i],h=q.high?.[i],l=q.low?.[i];if(![c,h,l].every(Number.isFinite))continue;out.push({t:r.timestamp[i],c:+c.toFixed(5),h:+h.toFixed(5),l:+l.toFixed(5)})}return out}
async function pool(items,limit,fn){let n=0;await Promise.all(Array.from({length:limit},async()=>{while(true){const i=n++;if(i>=items.length)break;await fn(items[i],i)}}))}
async function earnings(){const dates=[],now=new Date();for(let o=0;o<=13;o++){const d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()+o));if(d.getUTCDay()!==0&&d.getUTCDay()!==6)dates.push(`${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-${pad(d.getUTCDate())}`)}const events={},headers={'User-Agent':'Mozilla/5.0 AppleWebKit/537.36 Chrome/120 Safari/537.36','Accept':'application/json,text/plain,*/*','Accept-Language':'en-US,en;q=0.9','Referer':'https://www.nasdaq.com/market-activity/earnings'};let ok=0;for(const date of dates){try{const r=await fetch(`https://api.nasdaq.com/api/calendar/earnings?date=${date}`,{headers});if(!r.ok)continue;const j=await r.json(),rows=Array.isArray(j?.data?.rows)?j.data.rows:[];ok++;for(const row of rows){const s=String(row?.symbol||'').toUpperCase().trim();if(TICKERS.includes(s)&&!events[s])events[s]={date,time:row?.time||null,name:row?.name||null}}}catch{}await sleep(120)}return{complete:ok===dates.length,events,datesChecked:dates.length,datesSucceeded:ok}}
await fs.mkdir(path.dirname(OUT),{recursive:true});let old={};try{old=JSON.parse(await fs.readFile(OUT,'utf8'))}catch{}const today=new Date().toISOString().slice(0,10),daily=old.daily||{},hourly={},errors=[];const refreshDaily=old.dailyAsOf!==today||Object.keys(daily).length<TICKERS.length;const now=Date.now(),dailyStart=Math.floor((now-18*365.25*86400000)/1000),hourStart=Math.floor((now-35*86400000)/1000),end=Math.floor((now+86400000)/1000);
console.log(`Daily refresh: ${refreshDaily}`);await pool(TICKERS,3,async(t,i)=>{try{if(refreshDaily){daily[t]=dailyRows(await yahoo(t,dailyStart,end,'1d'));if(daily[t].length<2500)throw Error('not enough daily rows')}hourly[t]=hourlyRows(await yahoo(t,hourStart,end,'60m'));console.log(`${i+1}/${TICKERS.length} ${t}: ${daily[t]?.length||0}d ${hourly[t].length}h`)}catch(e){errors.push(`${t}: ${e.message}`);if(old.hourly?.[t])hourly[t]=old.hourly[t]}await sleep(180)});const e=await earnings();const usable=TICKERS.filter(t=>Array.isArray(daily[t])&&daily[t].length>2500).length;if(usable<45)throw Error(`Only ${usable}/50 tickers have daily history; refusing to publish.`);const market={version:4,generatedAt:new Date().toISOString(),dailyAsOf:refreshDaily?today:(old.dailyAsOf||today),scanSize:TICKERS.length,usableTickers:usable,daily,hourly,earnings:e,errors};await fs.writeFile(OUT,JSON.stringify(market));console.log(`Wrote ${OUT}; ${(JSON.stringify(market).length/1048576).toFixed(1)} MB`);
